_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    NAME: "AuxRes5ROIHeads"
    NUM_CLASSES: 80
    FREEZE_FEAT: True
    CLS_DROPOUT: True
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.01
    OUTPUT_LAYER: "AuxFastRCNNOutputLayers"
AUX_MODEL:
  SEMANTIC_DIM: 512
  INFERENCE_WITH_AUX: False
  KD_TEMPERATURE: 5.0
  WEIGHT_KD: 5.0
  WEIGHT_CE: 1.0
  KD_ALPHA: 0.5
  KD_BETA: 4.0
DATASETS:
  TRAIN: ('coco14_trainval_all_1shot_seedx',)
  TEST: ('coco14_test_all',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.005
  STEPS: (5120,)
  MAX_ITER: 6400
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "/Path/to/ImageNet/Pre-Train/Weight"
OUTPUT_DIR: "/Path/to/Output/Dir"