_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/Base/Pretrain/Weight"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    NAME: "AuxRes5ROIHeads"
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.001
    NUM_CLASSES: 20
    FREEZE_FEAT: True
    CLS_DROPOUT: True
    OUTPUT_LAYER: "AuxFastRCNNOutputLayers"
AUX_MODEL:
  SEMANTIC_DIM: 512
  INFERENCE_WITH_AUX: False
  KD_TEMPERATURE: 10.0
  WEIGHT_KD: 1.0
  WEIGHT_CE: 1.0
  KD_ALPHA: 0.2
  KD_BETA: 10.0
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ("voc_2007_trainval_allx_3shot_seedx", )
  TEST: ('voc_2007_test_allx',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.005
  STEPS: (3200,)
  MAX_ITER: 4000
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "/Path/to/ImageNet/Pre-Train/Weight"
OUTPUT_DIR: "/Path/to/Output/Dir"